package es.tekniker.eefrmwrk.database.sql.model;

// Generated Mar 4, 2013 4:57:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Alarm generated by hbm2java
 */
public class Alarm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 896090547923538691L;
	public final static String STATE_PENDING ="PENDING";
	public final static String STATE_CHECKED ="CHECKED";
	public final static String STATE_PROCESSING ="PROCESSING";
	public final static String STATE_CANCELLED ="CANCELLED";
	public static final String RULE_NOT_FOUND = "Rule not found";
	public static final Object OverType = "OverType";
	public static final Object UnderType ="UnderType";
	public static final Object EqualType = "EqualType";
	public static final Object NoEventType = "NoEventType";
	
	private long alarmId;
	private String alarmCode;
	private String alarmDesc;
	private String alarmMessage;
	private long alarmSeverity;
	private String alarmType;
	private Date alarmTimespan;
	private String alarmState;
	private long alarmDuedate;
	private long alarmUser;
	private long alarmRule;
	private long activ;

	public Alarm() {
	}

	public Alarm(String alarmCode, String alarmMessage, long alarmSeverity,
			String alarmType, Date alarmTimespan, String alarmState) {
		this.alarmCode = alarmCode;
		this.alarmMessage = alarmMessage;
		this.alarmSeverity = alarmSeverity;
		this.alarmType = alarmType;
		this.alarmTimespan = alarmTimespan;
		this.alarmState = alarmState;
	}

	public Alarm(String alarmCode, String alarmDesc, String alarmMessage,
			long alarmSeverity, String alarmType, Date alarmTimespan,
			String alarmState, long alarmDuedate, long alarmUser,
			long alarmRule, long activ) {
		this.alarmCode = alarmCode;
		this.alarmDesc = alarmDesc;
		this.alarmMessage = alarmMessage;
		this.alarmSeverity = alarmSeverity;
		this.alarmType = alarmType;
		this.alarmTimespan = alarmTimespan;
		this.alarmState = alarmState;
		this.alarmDuedate = alarmDuedate;
		this.alarmUser = alarmUser;
		this.alarmRule = alarmRule;
		this.activ = activ;
	}

	public long getAlarmId() {
		return this.alarmId;
	}

	public void setAlarmId(long alarmId) {
		this.alarmId = alarmId;
	}

	public String getAlarmCode() {
		return this.alarmCode;
	}

	public void setAlarmCode(String alarmCode) {
		this.alarmCode = alarmCode;
	}

	public String getAlarmDesc() {
		return this.alarmDesc;
	}

	public void setAlarmDesc(String alarmDesc) {
		this.alarmDesc = alarmDesc;
	}

	public String getAlarmMessage() {
		return this.alarmMessage;
	}

	public void setAlarmMessage(String alarmMessage) {
		this.alarmMessage = alarmMessage;
	}

	public long getAlarmSeverity() {
		return this.alarmSeverity;
	}

	public void setAlarmSeverity(long alarmSeverity) {
		this.alarmSeverity = alarmSeverity;
	}

	public String getAlarmType() {
		return this.alarmType;
	}

	public void setAlarmType(String alarmType) {
		this.alarmType = alarmType;
	}

	public Date getAlarmTimespan() {
		return this.alarmTimespan;
	}

	public void setAlarmTimespan(Date alarmTimespan) {
		this.alarmTimespan = alarmTimespan;
	}

	public String getAlarmState() {
		return this.alarmState;
	}

	public void setAlarmState(String alarmState) {
		this.alarmState = alarmState;
	}

	public long getAlarmDuedate() {
		return this.alarmDuedate;
	}

	public void setAlarmDuedate(long alarmDuedate) {
		this.alarmDuedate = alarmDuedate;
	}

	public long getAlarmUser() {
		return this.alarmUser;
	}

	public void setAlarmUser(long alarmUser) {
		this.alarmUser = alarmUser;
	}

	public long getAlarmRule() {
		return this.alarmRule;
	}

	public void setAlarmRule(long alarmRule) {
		this.alarmRule = alarmRule;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

}
