package es.tekniker.eefrmwrk.database.sql.model;

// Generated Oct 10, 2013 3:50:28 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Alert generated by hbm2java
 */
public class Alert implements java.io.Serializable {

	private long alertId;
	private long alertAlarm;
	private String alertMessage;
	private Date alertTimestamp;
	private String alertStatus;
	private long activ;

	public Alert() {
	}

	public Alert(long alertAlarm, String alertMessage, Date alertTimestamp,
			String alertStatus, long activ) {
		this.alertAlarm = alertAlarm;
		this.alertMessage = alertMessage;
		this.alertTimestamp = alertTimestamp;
		this.alertStatus = alertStatus;
		this.activ = activ;
	}

	public long getAlertId() {
		return this.alertId;
	}

	public void setAlertId(long alertId) {
		this.alertId = alertId;
	}

	public long getAlertAlarm() {
		return this.alertAlarm;
	}

	public void setAlertAlarm(long alertAlarm) {
		this.alertAlarm = alertAlarm;
	}

	public String getAlertMessage() {
		return this.alertMessage;
	}

	public void setAlertMessage(String alertMessage) {
		this.alertMessage = alertMessage;
	}

	public Date getAlertTimestamp() {
		return this.alertTimestamp;
	}

	public void setAlertTimestamp(Date alertTimestamp) {
		this.alertTimestamp = alertTimestamp;
	}

	public String getAlertStatus() {
		return this.alertStatus;
	}

	public void setAlertStatus(String alertStatus) {
		this.alertStatus = alertStatus;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

}
