package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 7, 2012 8:28:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * CepEngine generated by hbm2java
 */
public class CepEngine extends DBInstance implements java.io.Serializable {

	private long cengId;
	private String cengUrl;
	private String cengDesc;
	private long activ;

	public CepEngine() {
	}

	public CepEngine(String cengUrl) {
		this.cengUrl = cengUrl;
	}

	public CepEngine(String cengUrl, String cengDesc) {
		this.cengUrl = cengUrl;
		this.cengDesc = cengDesc;
	}

	public long getCengId() {
		return this.cengId;
	}

	public void setCengId(long cengId) {
		this.cengId = cengId;
	}

	public String getCengUrl() {
		return this.cengUrl;
	}

	public void setCengUrl(String cengUrl) {
		this.cengUrl = cengUrl;
	}

	public String getCengDesc() {
		return this.cengDesc;
	}

	public void setCengDesc(String cengDesc) {
		this.cengDesc = cengDesc;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getCengId();
	}

}
