package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 12, 2012 3:47:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * CepRuleStage generated by hbm2java
 */
public class CepRuleStage extends DBInstance implements java.io.Serializable {

	private long id;
	private long stageId;
	private long cepId;

	public CepRuleStage() {
	}

	public CepRuleStage(long stageId, long cepId) {
		this.stageId = stageId;
		this.cepId = cepId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getStageId() {
		return this.stageId;
	}

	public void setStageId(long stageId) {
		this.stageId = stageId;
	}

	public long getCepId() {
		return this.cepId;
	}

	public void setCepId(long cepId) {
		this.cepId = cepId;
	}

}
