package es.tekniker.eefrmwrk.database.sql.model;

// Generated Dec 18, 2014 4:54:46 PM by Hibernate Tools 3.6.0

/**
 * CepRule generated by hbm2java
 */
public class CepRule implements java.io.Serializable {

	private long cepId;
	private long cepEngine;
	private String cepName;
	private String cepEpl;
	private String cepListener;
	private long cepSeverity;
	private String cepMessage;
	private long activ;

	public CepRule() {
	}

	public CepRule(long cepEngine, String cepName, long activ) {
		this.cepEngine = cepEngine;
		this.cepName = cepName;
		this.activ = activ;
	}

	public CepRule(long cepEngine, String cepName, String cepEpl,
			String cepListener, long cepSeverity, String cepMessage, long activ) {
		this.cepEngine = cepEngine;
		this.cepName = cepName;
		this.cepEpl = cepEpl;
		this.cepListener = cepListener;
		this.cepSeverity = cepSeverity;
		this.cepMessage = cepMessage;
		this.activ = activ;
	}

	public long getCepId() {
		return this.cepId;
	}

	public void setCepId(long cepId) {
		this.cepId = cepId;
	}

	public long getCepEngine() {
		return this.cepEngine;
	}

	public void setCepEngine(long cepEngine) {
		this.cepEngine = cepEngine;
	}

	public String getCepName() {
		return this.cepName;
	}

	public void setCepName(String cepName) {
		this.cepName = cepName;
	}

	public String getCepEpl() {
		return this.cepEpl;
	}

	public void setCepEpl(String cepEpl) {
		this.cepEpl = cepEpl;
	}

	public String getCepListener() {
		return this.cepListener;
	}

	public void setCepListener(String cepListener) {
		this.cepListener = cepListener;
	}

	public long getCepSeverity() {
		return this.cepSeverity;
	}

	public void setCepSeverity(long cepSeverity) {
		this.cepSeverity = cepSeverity;
	}

	public String getCepMessage() {
		return this.cepMessage;
	}

	public void setCepMessage(String cepMessage) {
		this.cepMessage = cepMessage;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

}

