package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ChangeLog generated by hbm2java
 */
public class ChangeLog extends DBInstance implements java.io.Serializable {

	private long changeId;
	private String changeTable;
	private long changeTargetid;
	private String changeAction;
	private Date changeTimestamp;
	private String changeOld;
	private String changeNew;
	private String changeCol;

	public ChangeLog() {
	}

	public ChangeLog(String changeTable, String changeAction,
			Date changeTimestamp) {
		this.changeTable = changeTable;
		this.changeAction = changeAction;
		this.changeTimestamp = changeTimestamp;
	}

	public ChangeLog(String changeTable, long changeTargetid,
			String changeAction, Date changeTimestamp, String changeOld,
			String changeNew, String changeCol) {
		this.changeTable = changeTable;
		this.changeTargetid = changeTargetid;
		this.changeAction = changeAction;
		this.changeTimestamp = changeTimestamp;
		this.changeOld = changeOld;
		this.changeNew = changeNew;
		this.changeCol = changeCol;
	}

	public long getChangeId() {
		return this.changeId;
	}

	public void setChangeId(long changeId) {
		this.changeId = changeId;
	}

	public String getChangeTable() {
		return this.changeTable;
	}

	public void setChangeTable(String changeTable) {
		this.changeTable = changeTable;
	}

	public long getChangeTargetid() {
		return this.changeTargetid;
	}

	public void setChangeTargetid(long changeTargetid) {
		this.changeTargetid = changeTargetid;
	}

	public String getChangeAction() {
		return this.changeAction;
	}

	public void setChangeAction(String changeAction) {
		this.changeAction = changeAction;
	}

	public Date getChangeTimestamp() {
		return this.changeTimestamp;
	}

	public void setChangeTimestamp(Date changeTimestamp) {
		this.changeTimestamp = changeTimestamp;
	}

	public String getChangeOld() {
		return this.changeOld;
	}

	public void setChangeOld(String changeOld) {
		this.changeOld = changeOld;
	}

	public String getChangeNew() {
		return this.changeNew;
	}

	public void setChangeNew(String changeNew) {
		this.changeNew = changeNew;
	}

	public String getChangeCol() {
		return this.changeCol;
	}

	public void setChangeCol(String changeCol) {
		this.changeCol = changeCol;
	}

	@Override
	public long getId() {
		
		return getChangeId();
	}

}
