package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * Device generated by hbm2java
 */
public class Device extends DBInstance implements java.io.Serializable {

	private long devId;
	private String devName;
	private String devUri;
	private String devDesc;
	private String devStatus;
	private String devInfo;
	private long devLocalization;
	private String devCapabilities;
	private long activ;

	public Device() {
	}

	public Device(String devName, String devUri) {
		this.devName = devName;
		this.devUri = devUri;
	}

	public Device(String devName, String devUri, String devDesc,
			String devStatus, String devInfo, long devLocalization,
			String devCapabilities) {
		this.devName = devName;
		this.devUri = devUri;
		this.devDesc = devDesc;
		this.devStatus = devStatus;
		this.devInfo = devInfo;
		this.devLocalization = devLocalization;
		this.devCapabilities = devCapabilities;
	}

	public long getDevId() {
		return this.devId;
	}

	public void setDevId(long devId) {
		this.devId = devId;
	}

	public String getDevName() {
		return this.devName;
	}

	public void setDevName(String devName) {
		this.devName = devName;
	}

	public String getDevUri() {
		return this.devUri;
	}

	public void setDevUri(String devUri) {
		this.devUri = devUri;
	}

	public String getDevDesc() {
		return this.devDesc;
	}

	public void setDevDesc(String devDesc) {
		this.devDesc = devDesc;
	}

	public String getDevStatus() {
		return this.devStatus;
	}

	public void setDevStatus(String devStatus) {
		this.devStatus = devStatus;
	}

	public String getDevInfo() {
		return this.devInfo;
	}

	public void setDevInfo(String devInfo) {
		this.devInfo = devInfo;
	}

	public long getDevLocalization() {
		return this.devLocalization;
	}

	public void setDevLocalization(long devLocalization) {
		this.devLocalization = devLocalization;
	}

	public String getDevCapabilities() {
		return this.devCapabilities;
	}

	public void setDevCapabilities(String devCapabilities) {
		this.devCapabilities = devCapabilities;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getDevId();
	}

}
