package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * Home generated by hbm2java
 */
public class Home extends DBInstance implements java.io.Serializable {

	private long hiId;
	private String hiName;
	private String hiEndpoint;
	private long hiLocalization;
	private long activ;

	public Home() {
	}

	public Home(String hiName) {
		this.hiName = hiName;
	}

	public Home(String hiName, String hiEndpoint, long hiLocalization) {
		this.hiName = hiName;
		this.hiEndpoint = hiEndpoint;
		this.hiLocalization = hiLocalization;
	}

	public long getHiId() {
		return this.hiId;
	}

	public void setHiId(long hiId) {
		this.hiId = hiId;
	}

	public String getHiName() {
		return this.hiName;
	}

	public void setHiName(String hiName) {
		this.hiName = hiName;
	}

	public String getHiEndpoint() {
		return this.hiEndpoint;
	}

	public void setHiEndpoint(String hiEndpoint) {
		this.hiEndpoint = hiEndpoint;
	}

	public long getHiLocalization() {
		return this.hiLocalization;
	}

	public void setHiLocalization(long hiLocalization) {
		this.hiLocalization = hiLocalization;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getHiId();
	}

}
