package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * HomeDevice generated by hbm2java
 */
public class HomeDevice extends DBInstance implements java.io.Serializable {

	private long id;
	private long hiId;
	private long devId;

	public HomeDevice() {
	}

	public HomeDevice(long hiId, long devId) {
		this.hiId = hiId;
		this.devId = devId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getHiId() {
		return this.hiId;
	}

	public void setHiId(long hiId) {
		this.hiId = hiId;
	}

	public long getDevId() {
		return this.devId;
	}

	public void setDevId(long devId) {
		this.devId = devId;
	}

}
