package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * HomeVarMetadata generated by hbm2java
 */
public class HomeVarMetadata extends DBInstance implements java.io.Serializable {

	private long id;
	private long hiId;
	private long vmdId;

	public HomeVarMetadata() {
	}

	public HomeVarMetadata(long hiId, long vmdId) {
		this.hiId = hiId;
		this.vmdId = vmdId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getHiId() {
		return this.hiId;
	}

	public void setHiId(long hiId) {
		this.hiId = hiId;
	}

	public long getVmdId() {
		return this.vmdId;
	}

	public void setVmdId(long vmdId) {
		this.vmdId = vmdId;
	}

}
