package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * Localization generated by hbm2java
 */
public class Localization extends DBInstance implements java.io.Serializable {

	private long locId;
	private String locName;
	private String locAdress;
	private String locZip;
	private String locCity;
	private String locCountry;
	private String locGridlocation;
	private long activ;

	public static final String LOCALIZATION_UNKNOWN = "Unknown localization";
	public static final String LOCALIZATION_UNAVALAIBLE = "Unavalaible localization";

	public Localization() {
	}

	public Localization(String locName) {
		this.locName = locName;
	}

	public Localization(String locName, String locAdress, String locZip,
			String locCity, String locCountry, String locGridlocation) {
		this.locName = locName;
		this.locAdress = locAdress;
		this.locZip = locZip;
		this.locCity = locCity;
		this.locCountry = locCountry;
		this.locGridlocation = locGridlocation;
	}

	public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}

	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	public String getLocAdress() {
		return this.locAdress;
	}

	public void setLocAdress(String locAdress) {
		this.locAdress = locAdress;
	}

	public String getLocZip() {
		return this.locZip;
	}

	public void setLocZip(String locZip) {
		this.locZip = locZip;
	}

	public String getLocCity() {
		return this.locCity;
	}

	public void setLocCity(String locCity) {
		this.locCity = locCity;
	}

	public String getLocCountry() {
		return this.locCountry;
	}

	public void setLocCountry(String locCountry) {
		this.locCountry = locCountry;
	}

	public String getLocGridlocation() {
		return this.locGridlocation;
	}

	public void setLocGridlocation(String locGridlocation) {
		this.locGridlocation = locGridlocation;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getLocId();
	}

}
