package es.tekniker.eefrmwrk.database.sql.model;

// Generated Dec 20, 2012 4:49:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OpcNode generated by hbm2java
 */
public class OpcNode implements java.io.Serializable {

	private long opcNodeId;
	private long opcServerId;
	private String opcNodename;
	private String opcNmspc;
	private long activ;

	public OpcNode() {
	}

	public OpcNode(long opcServerId, String opcNodename, String opcNmspc) {
		this.opcServerId = opcServerId;
		this.opcNodename = opcNodename;
		this.opcNmspc = opcNmspc;
	}

	public OpcNode(long opcServerId, String opcNodename, String opcNmspc,
			long activ) {
		this.opcServerId = opcServerId;
		this.opcNodename = opcNodename;
		this.opcNmspc = opcNmspc;
		this.activ = activ;
	}

	public long getOpcNodeId() {
		return this.opcNodeId;
	}

	public void setOpcNodeId(long opcNodeId) {
		this.opcNodeId = opcNodeId;
	}

	public long getOpcServerId() {
		return this.opcServerId;
	}

	public void setOpcServerId(long opcServerId) {
		this.opcServerId = opcServerId;
	}

	public String getOpcNodename() {
		return this.opcNodename;
	}

	public void setOpcNodename(String opcNodename) {
		this.opcNodename = opcNodename;
	}

	public String getOpcNmspc() {
		return this.opcNmspc;
	}

	public void setOpcNmspc(String opcNmspc) {
		this.opcNmspc = opcNmspc;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

}

