package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * OpcServer generated by hbm2java
 */
public class OpcServer extends DBInstance implements java.io.Serializable {

	private long opcServerId;
	private String opcUrl;
	private String opcDesc;
	private long activ;

	public OpcServer() {
	}

	public OpcServer(String opcUrl) {
		this.opcUrl = opcUrl;
	}

	public OpcServer(String opcUrl, String opcDesc) {
		this.opcUrl = opcUrl;
		this.opcDesc = opcDesc;
	}

	public long getOpcServerId() {
		return this.opcServerId;
	}

	public void setOpcServerId(long opcServerId) {
		this.opcServerId = opcServerId;
	}

	public String getOpcUrl() {
		return this.opcUrl;
	}

	public void setOpcUrl(String opcUrl) {
		this.opcUrl = opcUrl;
	}

	public String getOpcDesc() {
		return this.opcDesc;
	}

	public void setOpcDesc(String opcDesc) {
		this.opcDesc = opcDesc;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getOpcServerId();
	}

}
