package es.tekniker.eefrmwrk.database.sql.model;

// Generated Dec 20, 2012 4:49:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OpcSubscription generated by hbm2java
 */
public class OpcSubscription implements java.io.Serializable {

	private long opcSubId;
	private long opcNodeId;
	private long opcVmd;
	private long opcPubint;
	private String opcDatachange;
	private long activ;

	public OpcSubscription() {
	}

	public OpcSubscription(long opcNodeId, long opcVmd, String opcDatachange) {
		this.opcNodeId = opcNodeId;
		this.opcVmd = opcVmd;
		this.opcDatachange = opcDatachange;
	}

	public OpcSubscription(long opcNodeId, long opcVmd, long opcPubint,
			String opcDatachange, long activ) {
		this.opcNodeId = opcNodeId;
		this.opcVmd = opcVmd;
		this.opcPubint = opcPubint;
		this.opcDatachange = opcDatachange;
		this.activ = activ;
	}

	public long getOpcSubId() {
		return this.opcSubId;
	}

	public void setOpcSubId(long opcSubId) {
		this.opcSubId = opcSubId;
	}

	public long getOpcNodeId() {
		return this.opcNodeId;
	}

	public void setOpcNodeId(long opcNodeId) {
		this.opcNodeId = opcNodeId;
	}

	public long getOpcVmd() {
		return this.opcVmd;
	}

	public void setOpcVmd(long opcVmd) {
		this.opcVmd = opcVmd;
	}

	public long getOpcPubint() {
		return this.opcPubint;
	}

	public void setOpcPubint(long opcPubint) {
		this.opcPubint = opcPubint;
	}

	public String getOpcDatachange() {
		return this.opcDatachange;
	}

	public void setOpcDatachange(String opcDatachange) {
		this.opcDatachange = opcDatachange;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

}
