package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * Stage generated by hbm2java
 */
public class Stage extends DBInstance implements java.io.Serializable {

	private long stageId;
	private long stageOwner;
	private String stageDesc;
	private long activ;

	public Stage() {
	}

	public Stage(long stageOwner) {
		this.stageOwner = stageOwner;
	}

	public Stage(long stageOwner, String stageDesc) {
		this.stageOwner = stageOwner;
		this.stageDesc = stageDesc;
	}

	public long getStageId() {
		return this.stageId;
	}

	public void setStageId(long stageId) {
		this.stageId = stageId;
	}

	public long getStageOwner() {
		return this.stageOwner;
	}

	public void setStageOwner(long stageOwner) {
		this.stageOwner = stageOwner;
	}

	public String getStageDesc() {
		return this.stageDesc;
	}

	public void setStageDesc(String stageDesc) {
		this.stageDesc = stageDesc;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getStageId();
	}

}
