package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * Task generated by hbm2java
 */
public class Task extends DBInstance implements java.io.Serializable {

	private long taskId;
	private String taskVar;
	private String taskDev;
	private String taskName;
	private String taskDesc;
	private String taskPeriod;
	private String taskValue;
	private long activ;

	public Task() {
	}

	public Task(String taskName, String taskPeriod) {
		this.taskName = taskName;
		this.taskPeriod = taskPeriod;
	}

	public Task(String taskVar, String taskDev, String taskName,
			String taskDesc, String taskPeriod, String taskValue) {
		this.taskVar = taskVar;
		this.taskDev = taskDev;
		this.taskName = taskName;
		this.taskDesc = taskDesc;
		this.taskPeriod = taskPeriod;
		this.taskValue = taskValue;
	}

	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	public String getTaskVar() {
		return this.taskVar;
	}

	public void setTaskVar(String taskVar) {
		this.taskVar = taskVar;
	}

	public String getTaskDev() {
		return this.taskDev;
	}

	public void setTaskDev(String taskDev) {
		this.taskDev = taskDev;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public String getTaskDesc() {
		return this.taskDesc;
	}

	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}

	public String getTaskPeriod() {
		return this.taskPeriod;
	}

	public void setTaskPeriod(String taskPeriod) {
		this.taskPeriod = taskPeriod;
	}

	public String getTaskValue() {
		return this.taskValue;
	}

	public void setTaskValue(String taskValue) {
		this.taskValue = taskValue;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getTaskId();
	}

}
