package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  extends DBInstance implements java.io.Serializable {

	private long userId;
	private String userName;
	private String userLogin;
	private String userPassword;
	private String userRole;
	private long activ;

	public UserLogin() {
	}

	public UserLogin(String userName) {
		this.userName = userName;
	}

	public UserLogin(String userName, String userLogin, String userPassword,
			String userRole) {
		this.userName = userName;
		this.userLogin = userLogin;
		this.userPassword = userPassword;
		this.userRole = userRole;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		
		return getUserId();
	}

}
