package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserStage generated by hbm2java
 */
public class UserStage extends DBInstance  implements java.io.Serializable {

	private long id;
	private long stageId;
	private long userId;

	public UserStage() {
	}

	public UserStage(long stageId, long userId) {
		this.stageId = stageId;
		this.userId = userId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getStageId() {
		return this.stageId;
	}

	public void setStageId(long stageId) {
		this.stageId = stageId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

}
