package es.tekniker.eefrmwrk.database.sql.model;

// Generated Jan 20, 2015 9:53:58 AM by Hibernate Tools 4.3.1

/**
 * ValueVar generated by hbm2java
 */
public class ValueVar implements java.io.Serializable {

	private long vrId;
	private long vrVmd;
	private String vrValue;
	private long vrTimestamp;
	private long vrQuality;
	private long activ;

	public static final String VALUE_UNKNOW = "Unknown value";
	public static final String VALUE_UNAVALAIBLE = "Unavalaible value";
	
	public ValueVar() {
	}

	public ValueVar(long vrVmd, String vrValue, long vrTimestamp) {
		this.vrVmd = vrVmd;
		this.vrValue = vrValue;
		this.vrTimestamp = vrTimestamp;
		this.activ = 1;
	}

	public ValueVar(long vrVmd, String vrValue, long vrTimestamp,
			long vrQuality, long activ) {
		this.vrVmd = vrVmd;
		this.vrValue = vrValue;
		this.vrTimestamp = vrTimestamp;
		this.vrQuality = vrQuality;
		this.activ = activ;
	}

	public long getVrId() {
		return this.vrId;
	}

	public void setVrId(long vrId) {
		this.vrId = vrId;
	}

	public long getVrVmd() {
		return this.vrVmd;
	}

	public void setVrVmd(long vrVmd) {
		this.vrVmd = vrVmd;
	}

	public String getVrValue() {
		return this.vrValue;
	}

	public void setVrValue(String vrValue) {
		this.vrValue = vrValue;
	}

	public long getVrTimestamp() {
		return this.vrTimestamp;
	}

	public void setVrTimestamp(long vrTimestamp) {
		this.vrTimestamp = vrTimestamp;
	}

	public long getVrQuality() {
		return this.vrQuality;
	}

	public void setVrQuality(long vrQuality) {
		this.vrQuality = vrQuality;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

}
