package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Comparator;
import java.util.Date;

/**
 * ValueRead generated by hbm2java
 */
public class ValueRead extends DBInstance implements java.io.Serializable{

	private long vrId;
	private long vrVmd;
	private String vrValue;
	private Date vrTimestamp;
	private long vrQuality;
	private long activ;

	public static final String VALUE_UNKNOW = "Unknown value";
	public static final String VALUE_UNAVALAIBLE = "Unavalaible value";

	public ValueRead() {
	}

	public ValueRead(long vrVmd, String vrValue, Date vrTimestamp) {
		this.vrVmd = vrVmd;
		this.vrValue = vrValue;
		this.vrTimestamp = vrTimestamp;
		activ=1;
	}

	public ValueRead(long vrVmd, String vrValue, Date vrTimestamp,
			long vrQuality) {
		this.vrVmd = vrVmd;
		this.vrValue = vrValue;
		this.vrTimestamp = vrTimestamp;
		this.vrQuality = vrQuality;
	}

	public long getVrId() {
		return this.vrId;
	}

	public void setVrId(long vrId) {
		this.vrId = vrId;
	}

	public long getVrVmd() {
		return this.vrVmd;
	}

	public void setVrVmd(long vrVmd) {
		this.vrVmd = vrVmd;
	}

	public String getVrValue() {
		return this.vrValue;
	}

	public void setVrValue(Object vrValue) {
		this.vrValue = vrValue.toString();
	}

	public Date getVrTimestamp() {
		return this.vrTimestamp;
	}

	public void setVrTimestamp(Date vrTimestamp) {
		this.vrTimestamp = vrTimestamp;
	}

	public long getVrQuality() {
		return this.vrQuality;
	}

	public void setVrQuality(long vrQuality) {
		this.vrQuality = vrQuality;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getVrId();
	}
	
	
	public static class ValueRead_DateComparator implements Comparator<ValueRead>{
		@Override
		public int compare(ValueRead o1, ValueRead o2) {
			Date d1=o1.getVrTimestamp();
			Date d2=o2.getVrTimestamp();
			return d1.compareTo(d2);
		}
	}

}
