package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * VarMetadataStage generated by hbm2java
 */
public class VarMetadataStage extends DBInstance implements java.io.Serializable {

	private long id;
	private long stageId;
	private long vmdId;
	private Boolean opcPub;

	public VarMetadataStage() {
	}

	public VarMetadataStage(long stageId, long vmdId, Boolean opcPub) {
		this.stageId = stageId;
		this.vmdId = vmdId;
		this.opcPub = opcPub;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getStageId() {
		return this.stageId;
	}

	public void setStageId(long stageId) {
		this.stageId = stageId;
	}

	public long getVmdId() {
		return this.vmdId;
	}

	public void setVmdId(long vmdId) {
		this.vmdId = vmdId;
	}

	public Boolean getOpcPub() {
		return this.opcPub;
	}

	public void setOpcPub(Boolean opcPub) {
		this.opcPub = opcPub;
	}

}
