package es.tekniker.eefrmwrk.database.sql.model;

// Generated Sep 4, 2012 8:53:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * VarMetadata generated by hbm2java
 */
public class VarMetadata extends DBInstance implements java.io.Serializable {

	public final static String Cassandra="Cassandra";
	public final static String PostgreSQL="PostgreSQL";
	
	public final static String DigType_boolean="boolean";
	public final static String DigType_integer="integer";
	public final static String DigType_double="double";
	public final static String DigType_float="float";
	public final static String DigType_long="long";
	public final static String DigType_string="string";

	private long vmdId;
	private String vmdName;
	private long vmdLocalization;
	private String vmdPhytype;
	private String vmdDigtype;
	private String vmdMeasureunit;
	private String vmdUri;
	private String vmdAccess;
	private String vmdStoredbd;
	private String vmdDescription;
	private long activ;

	public VarMetadata() {
	}

	public VarMetadata(String vmdName, String vmdStoredbd, long activ) {
		this.vmdName = vmdName;
		this.vmdStoredbd = vmdStoredbd;
		this.activ = activ;
	}

	public VarMetadata(String vmdName, long vmdLocalization, String vmdPhytype,
			String vmdDigtype, String vmdMeasureunit, String vmdUri,
			String vmdAccess, String vmdStoredbd, String vmdDescription,
			long activ) {
		this.vmdName = vmdName;
		this.vmdLocalization = vmdLocalization;
		this.vmdPhytype = vmdPhytype;
		this.vmdDigtype = vmdDigtype;
		this.vmdMeasureunit = vmdMeasureunit;
		this.vmdUri = vmdUri;
		this.vmdAccess = vmdAccess;
		this.vmdStoredbd = vmdStoredbd;
		this.vmdDescription = vmdDescription;
		this.activ = activ;
	}

	public long getVmdId() {
		return this.vmdId;
	}

	public void setVmdId(long vmdId) {
		this.vmdId = vmdId;
	}

	public String getVmdName() {
		return this.vmdName;
	}

	public void setVmdName(String vmdName) {
		this.vmdName = vmdName;
	}

	public long getVmdLocalization() {
		return this.vmdLocalization;
	}

	public void setVmdLocalization(long vmdLocalization) {
		this.vmdLocalization = vmdLocalization;
	}

	public String getVmdPhytype() {
		return this.vmdPhytype;
	}

	public void setVmdPhytype(String vmdPhytype) {
		this.vmdPhytype = vmdPhytype;
	}

	public String getVmdDigtype() {
		return this.vmdDigtype;
	}

	public void setVmdDigtype(String vmdDigtype) {
		this.vmdDigtype = vmdDigtype;
	}

	public String getVmdMeasureunit() {
		return this.vmdMeasureunit;
	}

	public void setVmdMeasureunit(String vmdMeasureunit) {
		this.vmdMeasureunit = vmdMeasureunit;
	}

	public String getVmdUri() {
		return this.vmdUri;
	}

	public void setVmdUri(String vmdUri) {
		this.vmdUri = vmdUri;
	}

	public String getVmdAccess() {
		return this.vmdAccess;
	}

	public void setVmdAccess(String vmdAccess) {
		this.vmdAccess = vmdAccess;
	}

	public String getVmdStoredbd() {
		return this.vmdStoredbd;
	}

	public void setVmdStoredbd(String vmdStoredbd) {
		this.vmdStoredbd = vmdStoredbd;
	}

	public String getVmdDescription() {
		return this.vmdDescription;
	}

	public void setVmdDescription(String vmdDescription) {
		this.vmdDescription = vmdDescription;
	}

	public long getActiv() {
		return this.activ;
	}

	public void setActiv(long activ) {
		this.activ = activ;
	}

	@Override
	public long getId() {
		return getVmdId();
	}
	
	
	public static boolean validStorage(String store) {
		return store.equals(Cassandra)
				|| store.equals(PostgreSQL);
	}
	
	public static boolean validDigType(String s){
		return  s==null||
				s.isEmpty()||
			    s.equals(DigType_boolean)||
				s.equals(DigType_double)||
				s.equals(DigType_float)||
				s.equals(DigType_integer)||
				s.equals(DigType_long)||
				s.equals(DigType_string);
	}

}
